[project]
name = "opd-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "datasets>=4.5.0",
    "deepspeed>=0.19.5",
    "ipykernel>=7.3.0",
    "math-verify>=0.9.0",
    "openai>=2.6.1",
    "openrlhf==0.11.0",
    "peft>=0.20.0",
    "pylatexenc>=2.11",
    "requests>=2.34.2",
    "streamlit",
    "transformers>=4.51.1,<5.0",
    "vllm==0.8.5",
]

[[tool.uv.dependency-metadata]]
name = "openrlhf"
version = "0.11.0"
requires-dist = []
